"""Suppression de app_id dans UtilisateurRole

Revision ID: 18c38a926219
Revises: 1582a3e49981
Create Date: 2025-02-28 12:11:39.439057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c38a926219'
down_revision = '1582a3e49981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur_role', schema=None) as batch_op:
        batch_op.drop_constraint('fk_utilisateur_role_app_id', type_='foreignkey')
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_utilisateur_role_app_id', 'application', ['app_id'], ['app_id'])

    # ### end Alembic commands ###
