"""Make date_expiration nullable

Revision ID: 1deff5bad3e8
Revises: 508a332b31f2
Create Date: 2025-03-05 15:45:45.336219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1deff5bad3e8'
down_revision = '508a332b31f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('prenom',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('date_expiration',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('creer_a',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('modifier_a',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint('uq_utilisateur_email', ['email'])
        batch_op.create_unique_constraint('uq_utilisateur_login', ['login'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_constraint('uq_utilisateur_login', type_='unique')
        batch_op.drop_constraint('uq_utilisateur_email', type_='unique')
        batch_op.alter_column('modifier_a',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('creer_a',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('date_expiration',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('prenom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
