"""Make app_id and app_icon nullable

Revision ID: 49eb56c0f603
Revises: 94cde5a6b046
Create Date: 2025-02-26 10:49:31.907147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49eb56c0f603'
down_revision = '94cde5a6b046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('app_icon',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('app_icon',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
