"""migration_endpoint_vers_fonction_api

Revision ID: 508a332b31f2
Revises: 82d9bcc694c0
Create Date: 2025-03-04 12:19:25.878133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508a332b31f2'
down_revision = '82d9bcc694c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonction_api',
    sa.Column('fonction_id', sa.Integer(), nullable=False),
    sa.Column('nom_fonction', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('fonction_id')
    )
    op.create_table('fonction_permission',
    sa.Column('fp_id', sa.Integer(), nullable=False),
    sa.Column('fonction_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonction_api.fonction_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ),
    sa.PrimaryKeyConstraint('fp_id')
    )
    op.drop_table('endpoint_permission')
    op.drop_table('endpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('url_pattern', sa.VARCHAR(length=300), nullable=False),
    sa.Column('methode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('app_id', sa.INTEGER(), nullable=False),
    sa.Column('creer_par', sa.INTEGER(), nullable=False),
    sa.Column('modifier_par', sa.INTEGER(), nullable=False),
    sa.Column('creer_a', sa.DATETIME(), nullable=False),
    sa.Column('modifier_a', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], name='fk_endpoint_app_id'),
    sa.PrimaryKeyConstraint('endpoint_id')
    )
    op.create_table('endpoint_permission',
    sa.Column('ep_id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.Column('creer_par', sa.INTEGER(), nullable=False),
    sa.Column('modifier_par', sa.INTEGER(), nullable=False),
    sa.Column('creer_a', sa.DATETIME(), nullable=False),
    sa.Column('modifier_a', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.endpoint_id'], name='fk_endpoint_permission_endpoint_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], name='fk_endpoint_permission_permission_id'),
    sa.PrimaryKeyConstraint('ep_id')
    )
    op.drop_table('fonction_permission')
    op.drop_table('fonction_api')
    # ### end Alembic commands ###
