"""add_valeur_and_modify_periode_in_objectif

Revision ID: 53fd0b5d92fb
Revises: 6ef188a6b762
Create Date: 2025-02-26 18:09:22.717202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fd0b5d92fb'
down_revision = '6ef188a6b762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valeur', sa.Float(), nullable=True))
        batch_op.alter_column('periode',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectif', schema=None) as batch_op:
        batch_op.alter_column('periode',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('valeur')

    # ### end Alembic commands ###
