"""add_app_id_to_objectif

Revision ID: 5aa28b1bc4b4
Revises: 5abd8d451860
Create Date: 2025-10-29 09:37:29.771731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa28b1bc4b4'
down_revision = '5abd8d451860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectif', schema=None) as batch_op:
        # Ajouter la colonne comme nullable d'abord
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
    
    # Mettre à jour tous les objectifs existants avec app_id = 1 (application par défaut)
    op.execute("UPDATE objectif SET app_id = 1 WHERE app_id IS NULL")
    
    # Maintenant rendre la colonne NOT NULL
    with op.batch_alter_table('objectif', schema=None) as batch_op:
        batch_op.alter_column('app_id', nullable=False)
        batch_op.create_foreign_key('fk_objectif_app_id', 'application', ['app_id'], ['app_id'])

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('creer_a',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('modifier_a',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('modifier_a',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('creer_a',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('objectif', schema=None) as batch_op:
        batch_op.drop_constraint('fk_objectif_app_id', type_='foreignkey')
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###
