"""add_objectif_table

Revision ID: 6ef188a6b762
Revises: 6f179b30f7d8
Create Date: 2025-02-26 17:46:45.296671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef188a6b762'
down_revision = '6f179b30f7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('periode', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('progression', sa.Float(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objectif')
    # ### end Alembic commands ###
