"""Make only date and action required in Trace model

Revision ID: 6f179b30f7d8
Revises: 49eb56c0f603
Create Date: 2025-02-26 15:15:51.243614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f179b30f7d8'
down_revision = '49eb56c0f603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('param',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('code_sql',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('end_point',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
        batch_op.alter_column('id_utilisateur',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace', schema=None) as batch_op:
        batch_op.alter_column('id_utilisateur',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_point',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
        batch_op.alter_column('code_sql',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('param',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
