"""Initial migration

Revision ID: 8ae0a290e12e
Revises: 
Create Date: 2025-02-25 11:08:28.688765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae0a290e12e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('app_color', sa.String(length=20), nullable=False),
    sa.Column('app_icon', sa.String(length=100), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('structure', sa.String(length=200), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('param', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('page',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lien', sa.String(length=300), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('profil', sa.String(length=50), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id_entite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_entite'], ['entite.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('id_utilisateur')
    )
    op.create_table('permission_page',
    sa.Column('pp_id', sa.Integer(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ),
    sa.PrimaryKeyConstraint('pp_id')
    )
    op.create_table('settings',
    sa.Column('id_set', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_codification', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_codification'], ['codification.id'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_set')
    )
    op.create_table('trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('param', sa.Text(), nullable=False),
    sa.Column('code_sql', sa.Text(), nullable=False),
    sa.Column('end_point', sa.String(length=400), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_demande',
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('nom_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delai_en_jour', sa.Integer(), nullable=True),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=True),
    sa.Column('creer_a', sa.DateTime(), nullable=True),
    sa.Column('modifier_a', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creer_par'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['modifier_par'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_type')
    )
    op.create_table('demande',
    sa.Column('id_demande', sa.Integer(), nullable=False),
    sa.Column('numero_demande', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contenu_sql', sa.Text(), nullable=True),
    sa.Column('chemin_fichier', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('niveau_priorite', sa.String(length=50), nullable=False),
    sa.Column('date_initiation', sa.DateTime(), nullable=False),
    sa.Column('date_prise_en_charge', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('id_utilisateur_demandeur', sa.Integer(), nullable=False),
    sa.Column('id_traiteur', sa.Integer(), nullable=True),
    sa.Column('id_type_demande', sa.Integer(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=True),
    sa.Column('creer_a', sa.DateTime(), nullable=True),
    sa.Column('modifier_a', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creer_par'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_traiteur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_type_demande'], ['types_demande.id_type'], ),
    sa.ForeignKeyConstraint(['id_utilisateur_demandeur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['modifier_par'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_demande'),
    sa.UniqueConstraint('numero_demande')
    )
    op.create_table('role_permission',
    sa.Column('rp_id', sa.Integer(), nullable=False),
    sa.Column('creer_par', sa.Integer(), nullable=False),
    sa.Column('modifier_par', sa.Integer(), nullable=False),
    sa.Column('creer_a', sa.DateTime(), nullable=False),
    sa.Column('modifier_a', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('pp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pp_id'], ['permission_page.pp_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('rp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission')
    op.drop_table('demande')
    op.drop_table('types_demande')
    op.drop_table('trace')
    op.drop_table('settings')
    op.drop_table('permission_page')
    op.drop_table('utilisateur')
    op.drop_table('page')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('entite')
    op.drop_table('codification')
    op.drop_table('black_list')
    op.drop_table('application')
    # ### end Alembic commands ###
