"""Add icon field to Page model

Revision ID: 94cde5a6b046
Revises: 8ae0a290e12e
Create Date: 2025-02-26 10:21:01.060551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cde5a6b046'
down_revision = '8ae0a290e12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
